version: '3.7'
services:
##### INFLUXDB
  influxdb:
    image: influxdb:1.8
    ports:
      - 8086:8086
    environment:
      DOCKER_INFLUXDB_HTTP_AUTH_ENABLED: "true"
      DOCKER_INFLUXDB_DB: ${INFLUXDB_DB}
      DOCKER_INFLUXDB_ADMIN_USER: ${INFLUXDB_ADMIN_USER}
      DOCKER_INFLUXDB_ADMIN_PASSWORD: ${INFLUXDB_ADMIN_PASSWORD}

    volumes:
      - ./data/influxdb:/var/lib/influxdb

##### TELEGRAF
  telegraf:
    image: telegraf
    ports:
      - 8186:8186
    environment:
      HOST_NAME: ${TELEGRAF_HOST_NAME}
      INFLUXDB_HOST: ${TELEGRAF_INFLUXDB_HOST}
      INFLUXDB_PORT: ${TELEGRAF_INFLUXDB_PORT}
      DATABASE: ${TELEGRAF_DATABASE}
    links:
      - "influxdb:influxdb"
    volumes:
      - ./telegraf.conf:/etc/telegraf/telegraf.conf
    tty: true
    privileged: true

##### CHRONOGRAF
  chronograf:
    image: chronograf
    ports:
      - 8888:8888
    command: ["chronograf", "--influxdb-url=http://influxdb:8086"]

##### KAPACITOR
  kapacitor:
    image: kapacitor
    environment:
      - KAPACITOR_INFLUXDB_0_URLS_0=http://influxdb:8086

##### GRAFANA
  grafana:
    image: grafana/grafana-oss:7.5.4
    ports:
      - 3000:3000
    links:
      - "influxdb:influxdb"
    environment:
      GF_SECURITY_ADMIN_USER: ${GF_ADMIN_USER}
      GF_SECURITY_ADMIN_PASSWORD: ${GF_ADMIN_PASSWORD}
    volumes:
      - ./data/grafana/grafana:/var/lib/grafana
    restart: always

##### MQTT
  mqtt:
    image: eclipse-mosquitto
    ports:
      - 1883:1883
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
    restart: always
